<a href="https://colab.research.google.com/github/pskarthikk/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

I chose the Content Opportunity Scoring lane. This is primarily a scoring/ranking machine learning task.

Each content page receives a score representing its likelihood of needing a content refresh. Editors can then prioritize pages with the highest scores instead of reviewing every page manually. A scoring approach is appropriate because it helps rank thousands of pages by priority rather than simply classifying them into two groups.

In [25]:
import nbformat

with open("./work/notebooks/w02_ml_task_framing.ipynb", "r", encoding="utf-8") as f:
    nb = nbformat.read(f, as_version=4)

for i, cell in enumerate(nb.cells):
    print("=" * 60)
    print(f"CELL {i} ({cell.cell_type})")
    print(cell.source)

============================================================
CELL 0 (markdown)
# ML-03 — Frame Your Lane as an ML Task

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.
============================================================
CELL 1 (markdown)
## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*
============================================================
CELL 2 (code)

============================================================
CELL 3 (markdown)
## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*
============================================================
CELL 4 (code)

============================================================
CELL 5 (markdown)
## 3. Success metric

*One metric you can defend. What number means 'good'?*
============================================================
CELL 6 (code)

============================================================
CELL 7 (markdown)
## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*
============================================================
CELL 8 (code)

============================================================
CELL 9 (markdown)
## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*
============================================================
CELL 10 (code)

============================================================
CELL 11 (markdown)
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

/usr/local/lib/python3.12/dist-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

In [26]:
!pwd
!ls

/content/flyrank-ml-internship/flyrank-ml-internship
AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission

In [27]:
!git clone https://github.com/pskarthikk/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 111 (delta 29), reused 77 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (111/111), 1.85 MiB | 16.58 MiB/s, done.
Resolving deltas: 100% (29/29), done.

In [28]:
%cd flyrank-ml-internship

/content/flyrank-ml-internship/flyrank-ml-internship/flyrank-ml-internship

In [29]:
!pwd

/content/flyrank-ml-internship/flyrank-ml-internship/flyrank-ml-internship

In [30]:
!find . -name "w02_ml_task_framing.ipynb"

./work/notebooks/w02_ml_task_framing.ipynb

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

In [31]:
ml_task_type = "Scoring / Ranking"

print("ML Task Type:", ml_task_type)

ML Task Type: Scoring / Ranking

The target is whether a content page should be prioritized for refresh.

Since there is no direct "needs refresh" label, a proxy target can be created using historical performance trends. Pages showing consistent declines in important performance metrics can be considered higher priority for refresh.

The model supports editorial decision making rather than making automatic publishing decisions.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

In [32]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Shape:", df.shape)

df.head()

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

A suitable success metric is **Precision@K**.

Editors usually have limited time, so the model should rank the most valuable refresh opportunities at the top. Precision@K measures how many of the highest-ranked recommendations are actually useful, making it appropriate for prioritization.

In [33]:
success_metric = "Precision@K"

print("Success Metric:", success_metric)

Success Metric: Precision@K

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

The unit of analysis is **one content page**.

Each row in the dataframe represents one content item together with its historical performance measurements and other available features that may help estimate refresh priority.

In [34]:
print("One row represents one content page.")

display(df.head())

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

One row represents one content page.

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

Number of rows: 30000
Number of columns: 44

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A fixed rule cannot easily capture the combined effects of many different features that influence content performance.

Machine learning can learn complex patterns from historical data and combine multiple signals when estimating refresh priority. This allows editors to focus on the pages that are most likely to benefit from updates instead of relying on simple thresholds.

In [35]:
# Example target column (illustration only)

df["target_refresh_priority"] = 0

display(df[["target_refresh_priority"]].head())

   target_refresh_priority
0                        0
1                        0
2                        0
3                        0
4                        0

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.